# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bloka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userb_acceptor', to='login.User')),
                ('blokr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userb_request', to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userf_acceptor', to='login.User')),
                ('userr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userf_request', to='login.User')),
            ],
        ),
    ]
